import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Particles from "./Effects/Particles";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const clashGrotesk = localFont({
  src:"./../public/fonts/TTF/ClashGrotesk-Variable.ttf",
  variable:"--font-clashGrotesk"
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative ${clashGrotesk.variable} `}>
            <div className="absolute w-full h-screen">
              <Particles particleColors={['#000000', '#000000']}
    particleCount={200}
    particleSpread={10}
    speed={0.1}
    particleBaseSize={100}
    moveParticlesOnHover={true}
    alphaParticles={false}
    disableRotation={false}
  />
        </div>
    
        {children}
      </body>
    </html>
  );
}
