import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const clashGrotesk = localFont({
  src:"./../public/fonts/TTF/ClashGrotesk-Variable.ttf",
  variable:"--font-clashGrotesk"
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased re ${clashGrotesk.variable} `}>
        {children}
      </body>
    </html>
  );
}
